FROM docker.io/library/maven as builder
WORKDIR /src
COPY . .
RUN mvn package

FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi

COPY --chown=1001:0 ejbserver-ear/src/main/liberty/config /config/

RUN features.sh

COPY --chown=1001:0 --from=builder /src/ejbserver-ear/target/ejbserver-ear.ear /config/apps

RUN configure.sh
