FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi

RUN featureUtility installFeature javaeeClient-7.0
RUN featureUtility installFeature appSecurityClient-1.0
RUN client create ejbclient
RUN mkdir /opt/ol/wlp/usr/clients/ejbclient/apps
COPY --chown=1001:0 client.xml /opt/ol/wlp/usr/clients/ejbclient
COPY --chown=1001:0 ejbclient-ear/target/ejbclient-ear.ear /opt/ol/wlp/usr/clients/ejbclient/apps
CMD [ "client", "run", "ejbclient" ]
